### PR TITLE
BREAKING CHANGE: hash_alg renamed to sd_hash_alg

### PR DESCRIPTION
**Pull request by peppelinux**
Closes https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/111

If this PR title is too noisy I can change it indeed, I use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Review by danielfett — APPROVED** [review]

**Comment by peppelinux** [comment]
> No need for shouting

They asked me to do that. Generally is often ask to italian to not be too loud and you can understand my embarrassment when I read they want make me shout, knowing that then someonelse will ask me to don't do that for sure.

Conventional shoutings?
If is there any suggetions :'-)

image

**Comment by danielfett** [comment]
Yes, I noticed that this prescribed by conventional commits :-) I guess I can get used to it.

**Comment by peppelinux** [comment]
> Yes, I noticed that this is prescribed by conventional commits :-) I guess I can get used to it.

now you have to shout it on the road for a concrete commitment!

**Review by Sakurann — APPROVED** [review]

**Comment by Sakurann** [comment]
here's to Daniel also shouting

**Pull request merged**
