### PR TITLE
clarify confusion around `_sd`

### PR DESCRIPTION
**Pull request by Sakurann**
As pointed out in the issuer #25, it is very confusing to have three separate objects that are all called `_sd`:
Renaming them as follows
`_sd` in SD-JWT -> `sd_hashes`
`_sd` in SVC -> `sd_container`
`_sd` in SD-JWT-R -> `_sd_container`

### CODE REVIEW

**Review by selfissued — CHANGES_REQUESTED** [review]
I agree that we should differentiate between these different claims.  However, per issue #4 , we should follow the convention of using the "_" prefix in the names of all meta-claims.  Please apply the prefix, then I will approve.  (That, or convince me that some of them are not meta-claims, and I'll also approve after that discussion.)

**Comment by bc-pi** [comment]
What's the reasoning for `_sd_container` and `sd_container`? They are the same thing. Just in different contexts.

**Comment by danielfett** [comment]
+1 for the underscore.

'container' is not very descriptive here, what about `_sd_releases`?

**Comment by bc-pi** [comment]
Aggregated and Distributed Claims are a rarely used corner of OIDC so calling that convention is a bit of an overstatement. Using an underscore as a halfhearted qualifier isn't really in the spirit of RFC7519's treatment of claim names either. 
Use an underscore if you want. But explain what it is supposed to mean. And register the claim. Don't assume it has special powers.

**Comment by Sakurann** [comment]
agreed to have two containers only: sd_digests and sd_release.
Kristina to investigate wrt the usage of `_` but leaning towards not using it as a starting point.

**Review by danielfett — APPROVED** [review]

**Pull request merged**
